;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	evil-exit-visual-state
	evil-force-normal-state
	evil-previous-line
	org-ctrl-c-ctrl-c
	))

(setq mc/cmds-to-run-once
      '(
	evil-next-line
	))
